id: AC348CD47
title: fDB83
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:24:00.683966
  last_modified_at: 2022-05-27 15:24:00.683969
